# Rustfmt configuration file (stable features only)
# This file configures code formatting for the project

# Edition to use
edition = "2021"

# Maximum width of each line
max_width = 100

# Number of spaces per tab
tab_spaces = 4

# Use hard tabs
hard_tabs = false

# Newline style
newline_style = "Unix"

# Use field init shorthand if possible
use_field_init_shorthand = true

# Use try shorthand
use_try_shorthand = true

# Reorder imports
reorder_imports = true

# Remove nested parens
remove_nested_parens = true

# Match block trailing comma
match_block_trailing_comma = false

# Force explicit types
force_explicit_abi = true
